apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftservertemplates.shulker.io
spec:
  group: shulker.io
  names:
    categories:
      - shulker
    kind: MinecraftServerTemplate
    listKind: MinecraftServerTemplateList
    plural: minecraftservertemplates
    shortNames:
      - mct
    singular: minecraftservertemplate
  scope: Namespaced
  versions:
    - name: v1beta1
      additionalPrinterColumns:
        - name: Parents
          jsonPath: .spec.parents
          type: string
        - name: Instances
          jsonPath: .status.instances
          format: int32
          type: number
        - name: Players
          jsonPath: .status.players
          format: int32
          type: number
        - name: Age
          jsonPath: .metadata.creationTimestamp
          type: date
      schema:
        openAPIV3Schema:
          description: 'A MinecraftServer resource describe how a Minecraft
            server should be created.'
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Desired state of the MinecraftServerTemplate resource.
              properties:
                inherit:
                  items:
                    description: 'List of MinecraftServerTemplate to inherit the
                      properties from.'
                    type: string
                  type: array
                version:
                  description: Describe the version of the Minecraft server to run.
                  properties:
                    name:
                      description: Litteral game version to run.
                      type: string
                    channel:
                      default: vanilla
                      description: Version distribution channel to use.
                      enum:
                        - vanilla
                      type: string
                  required:
                    - name
                  type: object
                count:
                  description: Limits to the number of instances the operator can deploy.
                  properties:
                    minimum:
                      description: Minimum count of Minecraft server instances to deploy.
                      format: int32
                      minimum: 0
                      type: integer
                    maximum:
                      description: Maximum count of Minecraft server instances to deploy.
                      format: int32
                      minimum: 1
                      type: integer
                  type: object
                playersCount:
                  description: Count of players a Minecraft server can accept.
                  format: int32
                  minimum: 1
                  type: integer
                additionalProperties:
                  additionalProperties:
                    type: string
                  description: 'Additional key-value properties to add to the
                    server.properties file.\n
                    Keys camelCased will be convertes to kebab-case.'
                  type: object
              type: object
            status:
              description: 'Status of the MinecraftServerTemplate. This is set and managed
                automatically.'
              properties:
                instances:
                  description: 'Count of instances using this MinecraftServerTemplate.'
                  format: int32
                  type: number
                players:
                  description: 'Count of players connected to the instances using this
                    MinecraftServerTemplate.'
                  format: int32
                  type: number
              type: object
      served: true
      storage: true
      subresources:
        status: {}
