name: cancel-ci

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    if: github.event.pull_request.draft == false

    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: 5310592 # https://api.github.com/repos/IamBlueSlime/Shulker/actions/workflows
